### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by lothsun** [jpbailey76/FF-Bot#2]
I was looking to use this to add our fantasy football league to our discord. Was Wondering if it still worked and all that. And a little help getting it set up would be nice.

**Comment by jpbailey76** [comment]
Hey @lothsun ,

This isn't maintained anymore but I do still host it on my friend group's Discord server which leads me to say that it should still be working in it's current state. If you run into any problems feel free to ask and I'll try and help you.

Follow these instructions to create and add your bot to your server: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token , and then after that all you need to know to setup the bot is:

- The FF-Bot works strictly for ESPN Fantasy Football leagues.
-  You must update your league_id / year in stats.py to reflect your chosen ESPN League ID and year of that league.
   That ID can be found in the URL when viewing your league. I.E.: **http://games.espn.com/ffl/leagueoffice?leagueId=1234567&seasonId=2017**
- You have to put your bot's OAuth token into the:
 `bot.run('TOKEN_HERE')`
call in the FFBot_cog.py file 
- Run the bot though the terminal by calling:
   `Python FFBot_cog.py`

I never really put the time and effort into this project that I would have liked but I have been planning on coming back to it when I have some free time. If you get everything set up and you don't mind it would be awesome if you could let me know some of the features you would like to see in a bot like this. I'll make sure to consider those while working on the new version.

Sorry for the delay. I hope this helps you some!

**Comment by thedahc** [comment]
I'm getting this error. What am I missing?

Traceback (most recent call last):
  File "C:\FFBot\FFBot_cog.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

**Comment by thedahc** [comment]
Hey, thanks for the guide. I got the bot running but I'm not sure what exactly it does. Does it have any commands? Or does this just pull information from ESPN FF League like weekly winners, etc? 

Do I need to add any webhook for this bot to have it work properly? Sorry, very new to this. 

I have the bot running and connected to my Discord server it seems. I show:

Logged in as:
FFBot
numbersomitted
======================
server name: 10th Annual LBK Fantasy League | server ID: numbersomitted

---------

I do not see any messages in my actual Discord server though I do see it connected. Am I missing anything or will this not pull information until we finish our draft and have the teams set up?

**Comment by lothsun** [comment]
When trying to start up the bot I get a syntax error on line 21

```File "FFBot_cog.py", line 21
    async def on_ready():
        ^
SyntaxError: invalid syntax```

**Comment by lothsun** [comment]
Should bot.event have () after it? and should it have any params inside the parenthesis?

**Comment by lothsun** [comment]
I'm not su[er familiar with python but I feel like I don't have some packages installed. Can someone help me? @thedahc

**Comment by jpbailey76** [comment]
That invalid syntax error is possibly an issue with your Python version as asynchronous requests aren't supported for any Python version prior to Python v3.3.  @lothsun
